#pragma once

enum {
    LED_CMD_GET_BOARD_INFO = 0xF0,
    LED_CMD_GET_FIRM_SUM = 0xF2,
    LED_CMD_GET_PROTOCOL_VER = 0xF3,
    LED_CMD_TIMEOUT = 0x11,
    LED_CMD_RESET = 0x10,
    LED_CMD_GET_BOARD_STATUS = 0xF1,
    LED_CMD_DISABLE_RESPONSE = 0x14,
    LED_CMD_SET_LED = 0x82,
    LED_CMD_SET_COUNT = 0x86,
    LED_CMD_BOOTLOADER = 0xFD,
    LED_CMD_MONKEY_RESET = 0xA0,
    LED_CMD_MONKEY_SET_SUM = 0xA1,
    LED_CMD_MONKEY_SET_TRANSLATION = 0xA2,
    LED_CMD_MONKEY_SET_CHANNELS = 0xA3,
    LED_CMD_MONKEY_SET_CHIP = 0xA4,
    LED_CMD_MONKEY_SET_FW_VER = 0xA5,
    LED_CMD_MONKEY_SET_BOARD_NAME = 0xA6,
    LED_CMD_MONKEY_SET_AUXILIARY_OUTPUT = 0xA7,
};